zakird/wkhtmltopdf_binary_gem

wkhtmltopdf-binary.gemspec

Under ruby 2.3.x bundler cannot install this gem as needed because the `require 'rake'` at the beginning of the `.gemspec` file breaks the installation process.

Don't require `rake` for ruby 2.3.x compatibility

---

bin/wkhtmltopdf

JRuby compatibility is now restored. It was previously broken by commit 41bf695 (https://github.com/zakird/wkhtmltopdf_binary_gem/commit/41bf695f32ebc09effde32837ca8d5c9e14602bc).
The problem was verified in but not limited to
jruby-1.7.4
jruby-1.7.13
jruby-1.7.16
jruby-1.7.16.1
jruby-1.7.19
The essence is that RbConfig::CONFIG['host'] returns nil in JRuby thus causing the Regex in the 'case' expression to fail and always raise an exception.
It is fixed by no longer relying on RbConfig::CONFIG['host'] but on RbConfig::CONFIG['host_os'] and RbConfig::CONFIG['host_cpu'] instead while being as 'concise' as possible.

JRuby compatibility

---

.docker/Dockerfile-centos_6
.docker/Dockerfile-centos_7
.docker/Dockerfile-debian_8
.docker/Dockerfile-debian_9
.docker/Dockerfile-ubuntu_14.04
.docker/Dockerfile-ubuntu_16.04
.docker/Dockerfile-ubuntu_18.04
.gitignore
CHANGELOG
README.md
Rakefile
bin/wkhtmltopdf
docker-compose.yml
test/test_with_docker.rb
wkhtmltopdf-binary.gemspec

Hello!
In reference to https://github.com/zakird/wkhtmltopdf_binary_gem/issues/46 I would like to propose this PR to update the wkhtmltopdf binaries to 0.12.5.
I extracted the binaries from https://wkhtmltopdf.org/downloads.html for:
- Ubuntu 18.04 (bionic) amd64 and i386
- Ubuntu 16.04 (xenial) amd64 and i386 
- macOS Cocoa 64-bit and Carbon 32-bit
The wrapper script was updated as well to support the different Ubuntu releases.
It still should only work on Ubuntu as it calls `lsb_release` to retrieve the codename. It was mentioned that the last version also only works on Ubuntu-based systems.
> 0.12.4 had the same issue, and we released a "good enough" version that worked on at least Ubuntu-based linux systems based on the binaries provided, and I think that's what we are looking for …

Update to 0.12.5

---

bin/wkhtmltopdf

Use latest ubuntu release binary to elementary os distro, because it is based in Ubuntu

Fix: Elementary OS distro

---

bin/wkhtmltopdf

This replaces the current process with wkhtmltopdf instead of running it in a subprocess. This way, when the process is killed, wkhtmltopdf won’t keep running as an orphan.

Use `exec` instead of `system`

---

.docker/Dockerfile-deepin
Rakefile
bin/wkhtmltopdf
docker-compose.yml
test/test_with_docker.rb

Hi everyone!
This PR will add check for Deepin OS for check what binary will be loaded. I see the work-around on this issue https://github.com/zakird/wkhtmltopdf_binary_gem/issues/62 but this is not totally satisfactory...
I'm try do test for a deepin image but I does not found a good Docker image. Can anyone help me with this test?
Thanks!
---
```bash
cat /etc/os-release
PRETTY_NAME="Deepin 15"
NAME="Deepin"
VERSION_ID="15.11"
VERSION="15.11"
ID=deepin
HOME_URL="https://www.deepin.org/"
BUG_REPORT_URL="http://feedback.deepin.org/feedback/"
```
I'm work with deepin on my laptop.
The Deepin is OS based on debian (some versions on unstable and other on stable):
_Deepin version X Debian Version table (by: https://en.wikipedia.org/wiki/Deepin)_

Deepin binary check

---

CHANGELOG
wkhtmltopdf-binary.gemspec

Closes #86 
Closes #82 
Closes https://github.com/zakird/wkhtmltopdf_binary_gem/pull/77
@unixmonkey 🤝

Add missing 0.12.6 binary for Ubuntu 20.04

---

CHANGELOG
bin/wkhtmltopdf
wkhtmltopdf-binary.gemspec

Closes https://github.com/zakird/wkhtmltopdf_binary_gem/pull/84
Closes https://github.com/zakird/wkhtmltopdf_binary_gem/issues/62
Closes https://github.com/zakird/wkhtmltopdf_binary_gem/issues/83
@unixmonkey Many distros are based on official supported OS's by wkhtmltopdf, to I made a little change to provide this mapping, without breaking any existing mapping, and 
also allow easily to add additional mapping in future 👍 
The current additional mappings:
Ubuntu 16.04, 16.10, 17.04, 17.10 -> 16.04
Elementary, Pop, Linux Mint, Ubuntu 18.04, 18.10, 19.04, 19.10 -> 18.04
Ubuntu 20.04, 20.10 -> 20.04
Amazon Linux 1 -> CentOS 6
Amazon Linux 2 -> CentOS 7
Deepin -> Debian 9

Organization of the OS mapping

---

bin/wkhtmltopdf

Adds the `WKHTMLTOPDF_HOST_SUFFIX` environment variable which can be used to override the default OS selection code. This allows users of non-standard, but compatible OS's to force the selection of the correct `wkhtmltopdf` binary

Permit overriding default OS

---

bin/wkhtmltopdf

The PR #60 adds support for Debian but it was only for Docker.
This adds a condition to make the `bin/wkhtmltopdf` file use the debian_10
binaries.
fixes #96

support Debian 10 and later on binary

---

bin/wkhtmltopdf

This pull request fixes issue#98.
https://github.com/zakird/wkhtmltopdf_binary_gem/issues/98
I tested on Debian 9. It failed with the original gem, and successfully worked with this pull request's patch.
```sh
$ docker run -it debian:9
Unable to find image 'debian:9' locally
9: Pulling from library/debian
4f250268ed6a: Pull complete 
Digest: sha256:bc125c699d736ac84c92b76ab7028741bbac69f207b7a8a4065bca6f79d5698e
Status: Downloaded newer image for debian:9
root@f3a23c1efa4b: cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@0751d68ff342: cd /root …
```

Prevent using the binary for Debian 10 when running on Debian 9

---

CHANGELOG
wkhtmltopdf-binary.gemspec

Includes the Debian 9 fix from https://github.com/zakird/wkhtmltopdf_binary_gem/pull/99

Version 0.12.6.5

---

bin/wkhtmltopdf

Invalid platform, must be running on Ubuntu 16.04/18.04/20.04 CentOS 6/7/8, Debian 9/10, archlinux amd64, or intel-based Cocoa macOS (missing binary: /home/username/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/wkhtmltopdf-binary-0.12.6.5/bin/wkhtmltopdf_zorin_15_amd64). (RuntimeError)

Add support to zorin OS

---

bin/wkhtmltopdf

This simply adds support for RHEL 7.x since it works with CentOS binaries.

Add support for RHEL 7.x

---

bin/wkhtmltopdf

Ubuntu 21.04 was released today, and currently this gem errors because it's not supported. I've installed wkhtmltopdf manually on my system using the binary for Focal Fossa (20.04) and it's working fine based on my testing.

Use the 20.04 binary for 21.04

---

.docker/Dockerfile-archlinux
.docker/Dockerfile-centos_6
.docker/Dockerfile-deepin
.github/workflows/ci.yml
.gitignore
CHANGELOG.md
Gemfile
README.md
bin/wkhtmltopdf
docker-compose.yml
test/test_with_docker.rb
wkhtmltopdf-binary.gemspec

Closes #114 
Hello, @unixmonkey ! 👋 
In order to provide us more automation in future PRs and changes, I added a complete Github Action workflow, that tests gem in all official base distros that we have binaries (including macos 🎉 ). Any derivated distro supported (deepin, amzn and so on) doesn't need (at least for a while) to be included in test suite.
Once this merged, we will get a stronger test suite in each change made in repo 🍻 
Let me know your impressions about it, it will be awesome 🤝 🤓 
Ps: You can check a example of the automation in this links, that contains the CI for last commit of PR: https://github.com/pedrofurtado/wkhtmltopdf_binary_gem/actions/runs/1061475630
Ps: None gem behavior was changed, and the CI is all green 🏁 ✅

GitHub actions automation 🤖 ✅ 

---

bin/wkhtmltopdf

Amazon Linux 2 os strings is "amzn_2" and Amazon Linux 1 os string version ID includes the year, for example: "amzn_2016.9".
This was causing all Amazon Linux to detect the binary as if it were Amazon Linux 2 and therefore failing on Amazon Linux 1.
This PR fixes the logic to make the detection work for both versions.

Fix logic to correctly detect Amazon Linux version

---

.github/workflows/ci.yml

Now the CI doesn't test with Ruby 3.0, but 3.1.
ref: https://bibwild.wordpress.com/2021/12/28/github-action-setup-ruby-needs-to-quote-3-0-or-will-end-up-with-ruby-3-1/

Add Ruby "3.0" support

---

.docker/Dockerfile-ubuntu_22.04
.gitignore
CHANGELOG.md
README.md
bin/wkhtmltopdf
docker-compose.yml
test/test_with_docker.rb
wkhtmltopdf-binary.gemspec

It has been a while since ubuntu 22.04 is out. this commit adds ubuntu 22.04 wkhtmltopdf binaries to the gem

Add support for Ubuntu 22.04

---

bin/wkhtmltopdf

This PR fixes platform detection for Linux Mint 20 and 21 releases.
Could not add a Docker test case as Mint does not have docker images.

Add support for Linux Mint 20 and 21

---

bin/wkhtmltopdf

Add support for tuxedo os: https://www.tuxedocomputers.com/en/TUXEDO-OS_1.tuxedo
Tuxedo Os 2 is based on ubuntu 22
There are no docker images for so I could not add it to the tests. This exact code is use on my pc as monkey patch to get it working.
Based on error:
`Invalid platform, must be running on Ubuntu 16.04/18.04/20.04/22.04, CentOS 6/7/8, Debian 9/10, Archlinux amd64, or Intel-based Cocoa macOS (missing binary: wkhtmltopdf_tuxedo_22.04_amd64). (RuntimeError)`

Add support for tuxedo os

---

wkhtmltopdf-binary.gemspec

It would be nice if there are links from https://rubygems.org/gems/wkhtmltopdf-binary to its source code and changelog. Of course, this information is useful not only for rubygems.org, but also for various update support tools.
It used to be possible to edit the URL at rubygems.org, but this is no longer possible, so I think it is preferable to include it in the gemspec.

Add some URLs to gemspec

---

.docker/Dockerfile-ubuntu_24.04
bin/wkhtmltopdf
test/test_with_docker.rb

Closes to https://github.com/zakird/wkhtmltopdf_binary_gem/issues/175
As mentioned by @unixmonkey, there's no official build for ubuntu24.04 on https://wkhtmltopdf.org/downloads.html.  
We could use the same binary used for `ubuntu_22.04`;  
This pull request includes updates to support Ubuntu 24.04 in the Docker setup and associated tests. The most important changes include adding a new Dockerfile for Ubuntu 24.04 and updating the test suite to include a test for Ubuntu 24.04.
* [`.docker/Dockerfile-ubuntu_24.04`](diffhunk://#diff-eae690bf8262f978a076b03c46580108402b6392d45744588b92584ec0a749f8R1-R8): Added a new Dockerfile for Ubuntu 24.04, setting up the environment and installing necessary packages.
* [`test/test_with_docker.rb`](diffhunk://#diff-87080b560a27041113dd2e708bdc05d4f9ef6e3 …

Add support to ubuntu 24.04

---

bin/wkhtmltopdf

The current code was written for supporting AWS AMI AL2. 
This causes a bug in Amazon Linux 2023 where it uses CentOS 6 build which is not suitable. This fixes the build to be used for Amazon Linux 2023 to CentOS 8.

Fix binary used for Amazon Linux 2023 AMI

---

bin/wkhtmltopdf

Add support for KDE Neon (Ubuntu derivative with KDE desktop) 22.04 and 24.04, which calls itself "neon" in /etc/os-release.

Update wkhtmltopdf: Support KDE Neon 22.04 and 24.04

---

.gitignore
docker-compose-arm.yml
test/test_with_docker.rb

The binary is the same for Ubuntu 22.04 and 24.04
> [!IMPORTANT]
> To check the binary is the same as the one from https://wkhtmltopdf.org/downloads.html before using and/or merging this branch, run the following:
> ```
> $ curl -L https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_arm64.deb > wkhtmltox_0.12.6.1-2.jammy_arm64.deb
> $ dpkg -x wkhtmltox_0.12.6.1-2.jammy_arm64.deb wkhtmltox/
> $ git clone -b add-ubuntu-24-04-arm --single-branch --depth 1 https://github.com/chileung-b4b/wkhtmltopdf_binary_gem.git
> $ gunzip -c ./wkhtmltopdf_binary_gem/bin/wkhtmltopdf_ubuntu_22.04_arm64.gz | sha256sum -
> 00fbba5e1ee392776c2978b45503c07af34c42086c842b31dc9d7a76d52fcf29  -
> $ sha256sum wkhtmltox/usr/local/bin/wkhtmltopdf
> …
```

Add support to ubuntu 22.04 and 24.04 in arm64
